// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Bid struct {
	ID        int    `json:"ID"`
	BidderID  int    `json:"bidder_id"`
	ProjectID int    `json:"project_id"`
	Price     int    `json:"price"`
	Comment   string `json:"comment"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type NewBid struct {
	ProjectID int    `json:"project_id"`
	Price     int    `json:"price"`
	Comment   string `json:"comment"`
}

type NewProject struct {
	CreatorID int    `json:"creator_id"`
	Name      string `json:"name"`
	Desc      string `json:"desc"`
	Price     int    `json:"price"`
	Deadline  string `json:"deadline"`
}

type Project struct {
	ID          int     `json:"ID"`
	CreatorID   int     `json:"creator_id"`
	Name        string  `json:"name"`
	Desc        string  `json:"desc"`
	Price       int     `json:"price"`
	PriceString *string `json:"priceString"`
	Deadline    string  `json:"deadline"`
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   string  `json:"updated_at"`
}
