// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Bid struct {
	ID          string   `json:"ID"`
	BidderID    string   `json:"bidder_id"`
	Bidder      *User    `json:"bidder"`
	ProjectID   string   `json:"project_id"`
	Project     *Project `json:"project"`
	Price       int      `json:"price"`
	PriceString *string  `json:"priceString"`
	Comment     string   `json:"comment"`
	CreatedAt   string   `json:"created_at"`
	UpdatedAt   string   `json:"updated_at"`
}

type Login struct {
	Uoe      string `json:"uoe"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token string `json:"token"`
}

type NewBid struct {
	ProjectID string `json:"project_id"`
	Price     int    `json:"price"`
	Comment   string `json:"comment"`
}

type NewProject struct {
	Name     string `json:"name"`
	Desc     string `json:"desc"`
	Price    int    `json:"price"`
	Deadline string `json:"deadline"`
}

type Project struct {
	ID          string  `json:"ID"`
	CreatorID   string  `json:"creator_id"`
	Creator     *User   `json:"creator"`
	Name        string  `json:"name"`
	Desc        string  `json:"desc"`
	Price       int     `json:"price"`
	PriceString *string `json:"priceString"`
	Deadline    string  `json:"deadline"`
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   string  `json:"updated_at"`
}

type Register struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type User struct {
	ID        string  `json:"ID"`
	Username  string  `json:"username"`
	Email     string  `json:"email"`
	Password  string  `json:"password"`
	FirstName *string `json:"first_name"`
	LastName  *string `json:"last_name"`
	CreatedAt string  `json:"created_at"`
	UpdatedAt string  `json:"updated_at"`
}
